type YBRpage = {
  id: string;
  title: string;
  phase: "I" | "P" | "O" | "W" | "E" | "R";
  phaseLabel: string;
  rank: "newb" | "cadet" | "learner" | "ranger";
};

export const YellowBrickRoad: YBRpage[] = [
  {
    id: "MeetTutor",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "FeelThePower",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "GratzWatchedVideo",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "FindTutor",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "GratzFoundTutor",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "ReadProblem",
    title: "string",
    phase: "P",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "KnownFacts",
    title: "string",
    phase: "P",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "GratzOnPrepare",
    title: "string",
    phase: "I",
    phaseLabel: "str",
    rank: "newb",
  },
  {
    id: "ReadProblem",
    title: "string",
    phase: "P",
    phaseLabel: "str",
    rank: "cadet",
  },
  {
    id: "WhatToAnswer",
    title: "Read the Problem",
    phase: "P",
    phaseLabel: "str",
    rank: "cadet",
  },
  {
    id: "FindFacts",
    title: "What are the relevant facts?",
    phase: "P",
    phaseLabel: "str",
    rank: "cadet",
  },
  {
    id: "SelectDiagram",
    title: "What type of problem is it?",
    phase: "O",
    phaseLabel: "str",
    rank: "cadet",
  },
  {
    id: "FillDiagram",
    title: "Fill in the Diagram",
    phase: "O",
    phaseLabel: "str",
    rank: "cadet",
  },
  {
    id: "FillEquation",
    title: "string",
    phase: "O",
    phaseLabel: "Fill in the Equation",
    rank: "cadet",
  },
  {
    id: "GratzOnOrganize",
    title: "string",
    phase: "I",
    phaseLabel: "",
    rank: "cadet",
  },
  {
    id: "SolveTheEquation",
    title: "Solve the Equation",
    phase: "W",
    phaseLabel: "Work the Problem",
    rank: "cadet",
  },
  {
    id: "GratzEquationSolved",
    title: "Congratulations you solved the equation",
    phase: "I",
    phaseLabel: "Work the Problem",
    rank: "cadet",
  },
  {
    id: "SolvedFor",
    title: "Do you remember what XXX is?",
    phase: "E",
    phaseLabel: "Explain your Answer",
    rank: "cadet",
  },
  {
    id: "Reflect",
    title: "Why is this answer correct?",
    phase: "R",
    phaseLabel: "Reflect on the Answer",
    rank: "cadet",
  },
  {
    id: "GratzOnLearner",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "cadet",
  },
  {
    id: "QuestIntro",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "cadet",
  },
  {
    id: "WhatIsPower",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "cadet",
  },

  {
    id: "ReadProblem",
    title: "string",
    phase: "P",
    phaseLabel: "str",
    rank: "ranger",
  },
  {
    id: "WhatToAnswer",
    title: "Read the Problem",
    phase: "P",
    phaseLabel: "str",
    rank: "ranger",
  },
  {
    id: "FindFacts",
    title: "What are the relevant facts?",
    phase: "P",
    phaseLabel: "str",
    rank: "ranger",
  },
  {
    id: "SelectDiagram",
    title: "What type of problem is it?",
    phase: "O",
    phaseLabel: "str",
    rank: "ranger",
  },
  {
    id: "FillDiagram",
    title: "Fill in the Diagram",
    phase: "O",
    phaseLabel: "str",
    rank: "ranger",
  },
  {
    id: "FillEquation",
    title: "string",
    phase: "O",
    phaseLabel: "Fill in the Equation",
    rank: "ranger",
  },
  {
    id: "GratzOnOrganize",
    title: "string",
    phase: "I",
    phaseLabel: "",
    rank: "ranger",
  },
  {
    id: "SolveTheEquation",
    title: "Solve the Equation",
    phase: "W",
    phaseLabel: "Work the Problem",
    rank: "ranger",
  },
  {
    id: "GratzEquationSolved",
    title: "Congratulations you solved the equation",
    phase: "I",
    phaseLabel: "Work the Problem",
    rank: "ranger",
  },
  {
    id: "SolvedFor",
    title: "Do you remember what XXX is?",
    phase: "E",
    phaseLabel: "Explain your Answer",
    rank: "ranger",
  },
  {
    id: "Reflect",
    title: "Why is this answer correct?",
    phase: "R",
    phaseLabel: "Reflect on the Answer",
    rank: "ranger",
  },
  {
    id: "GratzOnLearner",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "ranger",
  },
  {
    id: "QuestIntro",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "ranger",
  },
  {
    id: "WhatIsPower",
    title: "",
    phase: "I",
    phaseLabel: "",
    rank: "ranger",
  },
];
