import { Operator } from "../../stores/solution";

export const numberKeys: Operator[] = [
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "7",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "7",
    tooltip: "Seven",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "8",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "8",
    tooltip: "Eight",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "9",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "9",
    tooltip: "Nine",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "4",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "4",
    tooltip: "Four",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "5",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "5",
    tooltip: "Five",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "6",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "6",
    tooltip: "Six",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "1",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "1",
    tooltip: "One",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "2",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "2",
    tooltip: "Two",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "3",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "3",
    tooltip: "Three",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "0",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "0",
    tooltip: "Zero",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: ".",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ".",
    tooltip: "Decimal Separator",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: ",",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ",",
    tooltip: "Thousands Separator",
  },
];
