import { Operator } from "../../stores/solution";

export const stdOperators: Operator[] = [
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "*",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "*",
    tooltip: "Multiply",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "BKSP",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "PiBackspaceLight",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Backspace",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "DIVIDE",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "TiDivideOutline",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Divide",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "CLEAR",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "FaRegTrashCan",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Clear Step",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ADDITION",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "FaPlus",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Addition",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "SPACE",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "RiSpace",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Space",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "SUBTRACT",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "GrSubtract",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Subtract",
  },
  {
    method: "char",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "EQUAL",
    string: "",
    symbol_latex: "",
    symbol_style: { background: "none", fontSize: "1rem" },
    symbol_html: "",
    symbol_icon: "FaEquals",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Equal",
  },
];
