export const operators = [
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "(",
    mma: "",
    operator: "Parens",
    string: "(a)",
    symbol_latex: "\\left(\\placeholder[foo]{}\\right)",
    symbol_style: { background: "none", fontSize: ".6rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Parenthesis",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\left(",
    mma: "",
    operator: "(",
    string: "(",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "(",
    tooltip: "Open Parenthesis",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\right)",
    mma: "",
    operator: ")",
    string: ")",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ")",
    tooltip: "Close Parenthesis",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\[",
    mma: "",
    operator: "[",
    string: "[",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "[",
    tooltip: "Left Bracket",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\]",
    mma: "",
    operator: "]",
    string: "]",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "]",
    tooltip: "Right Bracket",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\{",
    mma: "",
    operator: "{",
    string: "{",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "{",
    tooltip: "Left Curly Brace",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\}",
    mma: "",
    operator: "}",
    string: "}",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "}",
    tooltip: "Right Curly Brace",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: ",",
    mma: "",
    operator: ",",
    string: ",",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ",",
    tooltip: "Comma",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: ".",
    mma: "",
    operator: ".",
    string: ".",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ".",
    tooltip: "Decimal",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\frac",
    mma: "",
    operator: "Frac",
    string: "Fraction",
    symbol_latex: "\\frac{\\placeholder[foo]{}}{\\placeholder[bar]{}}",
    symbol_style: { fontSize: ".5rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Fraction",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "|",
    mma: "",
    operator: "Abs",
    string: "|a|",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "<span>|<i>a</i>|</span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Absolute Value",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\sqrt",
    mma: "",
    operator: "SquareRoot",
    picture: "",
    string: "√",
    symbol_latex: "\\sqrt{\\placeholder[foo]{}}",
    symbol_style: { fontSize: ".75rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Root",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "^",
    mma: "",
    operator: "SuperScript",
    string: "^",
    symbol_latex: "\\placeholder[foo]{}^\\placeholder[bar]{}",
    symbol_style: { fontSize: ".75rem" },
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "SuperScript",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "f^{(-1)}()",
    mma: "",
    operator: "InverseFunction",
    string: "^",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>f</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'>&nbsp;&nbsp;‒1</span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "InverseFunction",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "_",
    mma: "",
    operator: "SubScript",
    string: "_",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "<var>a</var><sub><i>b</i></sub>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "SubScript",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\ast",
    mma: "",
    operator: "Multiply",
    string: "*",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "*",
    tooltip: "Multiply",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\div",
    mma: "÷",
    operator: "Divide",
    string: "÷",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "U+002F",
    tooltip: "Divide",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "=",
    mma: "",
    operator: "Equal",
    string: "=",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "=",
    tooltip: "Equals",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: true,
    latex: "\\lognat",
    mma: "",
    operator: "ln",
    string: "ln",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "ln",
    tooltip: "Natural Logarithm",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: true,
    latex: "\\logten",
    mma: "",
    operator: "log10",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "log",
    tooltip: "Common Logarithm",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\logb",
    mma: "",
    operator: "logb",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "log<sub><i>b</i></sub>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Logarithm base b",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "-",
    mma: "",
    operator: "Minus",
    string: "-",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "-",
    tooltip: "Minus",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "+",
    mma: "",
    operator: "Plus",
    string: "+",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "+",
    tooltip: "Plus",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\pm",
    mma: "",
    operator: "PlusMinus",
    string: "+/-",
    symbol_latex: "\\pm",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "±",
    tooltip: "Plus or Minus",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "Power",
    mma: "",
    operator: "Power",
    string: "Power",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Power",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\cdot",
    mma: "",
    operator: "Times",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "·",
    tooltip: "Times",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "NoAsymptotes",
    mma: "",
    operator: "NoAsymptotes",
    string: "NoAsymptotes",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "No Asymptotes",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\neq",
    mma: "",
    operator: "Unequal",
    string: "Not Equal",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "≠",
    tooltip: "Not Equal",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\nthroot",
    mma: "",
    operator: "Surd",
    string: "",
    symbol_latex: "\\sqrt[\\placeholder[foo]{}]{\\placeholder[bar]{}}",
    symbol_style: { fontSize: ".75rem" },
    symbol_html:
      "<span class='mq-math-mode qq-mq-surd'><sup class='mq-nthroot mq-non-leaf'><var>a</var></sup><span class='mq-scaled'><span class='mq-sqrt-prefix mq-scaled' style='transform: scale(1, 0.932609);'>√</span><span class='mq-sqrt-stem mq-non-leaf'><var>b</var></span></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Nth Root",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\sin()",
    mma: "",
    operator: "Sin",
    string: "sin",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "sin",
    tooltip: "Sine",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\cos()",
    mma: "",
    operator: "Cos",
    string: "cos",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "cos",
    tooltip: "Cosine",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\tan()",
    mma: "",
    operator: "Tan",
    string: "tan",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "tan",
    tooltip: "Tangent",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\sec()",
    mma: "",
    operator: "Sec",
    string: "sec",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "sec",
    tooltip: "Secant",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\csc()",
    mma: "",
    operator: "Csc",
    string: "csc",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "csc",
    tooltip: "Cosecant",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\cot()",
    mma: "",
    operator: "Cot",
    string: "cot",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "cot",
    tooltip: "Cotangent",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\cos^{-1}()",
    mma: "",
    operator: "ArcCos",
    string: "arccos",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "cos<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse cosine",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\cot^{-1}()",
    mma: "",
    operator: "ArcCot",
    string: "arccot",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "cot<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse cotangent",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\csc^{-1}()",
    mma: "",
    operator: "ArcCsc",
    string: "arccsc",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "csc<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse Cosecant",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\sec^{-1}()",
    mma: "",
    operator: "ArcSec",
    string: "arcsec",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "sec<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse Secant",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\sin^{-1}()",
    mma: "",
    operator: "ArcSin",
    string: "arcsin",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "sin<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse sine",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\tan^{-1}()",
    mma: "",
    operator: "ArcTan",
    string: "arctan",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "tan<sup>-1</sup>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inverse tangent",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\text{ And }",
    mma: "\\text{ And }",
    operator: "And",
    string: "&",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "And",
    tooltip: "And",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "False",
    mma: "",
    operator: "False",
    string: "False",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "False",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "True",
    mma: "",
    operator: "True",
    string: "True",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "True",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "YES",
    mma: "",
    operator: "YES",
    string: "YES",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "YES",
    tooltip: "Yes",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "NO",
    mma: "",
    operator: "NO",
    string: "NO",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "NO",
    tooltip: "No",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: ">",
    mma: "",
    operator: "Greater",
    string: ">",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: ">",
    tooltip: "Greater Than",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\geq",
    mma: "",
    operator: "GreaterEqual",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "≥",
    tooltip: "Greater Than or Equal To",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\neq",
    mma: "",
    operator: "Inequality",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "≠",
    tooltip: "Inequality",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "<",
    mma: "",
    operator: "Less",
    string: "<",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "<",
    tooltip: "Less Than",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\leq",
    mma: "",
    operator: "LessEqual",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "≤",
    tooltip: "Less Than or Equal To",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\neg",
    mma: "",
    operator: "Not",
    string: "Not",
    symbol_latex: "\\neg",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "¬",
    tooltip: "Not",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\text{ Or }",
    mma: "\\text{ Or }",
    operator: "Or",
    string: "Or",
    symbol_latex: "\\text{ Or }",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "Or",
    tooltip: "Or",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "Backspace",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "ion-backspace-outline",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Backspace",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "Clear",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "icon ion-trash-b",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Wipe It!",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "UndefinedSlope",
    mma: "UndefinedSlope",
    operator: "UndefinedSlope",
    string: "UndefinedSlope",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "|",
    tooltip: "Undefined Slope",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "Midpoint",
    mma: "",
    operator: "Midpoint",
    string: "Midpoint",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Midpoint",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "\\over{d}{dx}\\left(\\right)",
    mma: "",
    operator: "D",
    string: "d/dx",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<span class='mq-fraction mq-non-leaf'><span class='mq-numerator' mathquill-block-id='25'><span mathquill-command-id='27'><i>d</i></span></span><span class='mq-denominator' mathquill-block-id='26'><span mathquill-command-id='29'><i>dx</i></span></span><span style='display:inline-block;width:0'>&#8203;</span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Derivative with respect to x",
  },
  {
    method: "write",
    cursorShift: "←",
    atomic: false,
    enabled: false,
    latex: "d",
    mma: "",
    operator: "dd",
    string: "dd",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<span class='mq-fraction mq-non-leaf'><span class='mq-numerator' mathquill-block-id='25'><span mathquill-command-id='27'><i>d</i></span></span><span class='mq-denominator' mathquill-block-id='26'><span mathquill-command-id='29'><i>dx</i></span></span><span style='display:inline-block;width:0'>&#8203;</span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Differential For Int",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "'",
    mma: "",
    operator: "Prime",
    string: "'",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "'",
    tooltip: "Prime",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\eval",
    mma: "",
    operator: "EvaluationBar",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<span class='mq-math-mode qq-mq-int'><span class='mq-int mq-non-leaf'><big>|</big><span class='mq-supsub mq-non-leaf qq-mq-eval-supsub'><span class='mq-sup'><span class='mq-sup-inner'><var>b</var></span></span><span><var>a</var></span><span style='display:inline-block;width:0'></span></span></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Evaluation Bar",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\vert_",
    mma: "FindDerAt",
    operator: "FindDerAt",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Find the derivative at a given point",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "∫",
    mma: "",
    operator: "Integrate",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "∫",
    tooltip: "Integrate",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\int",
    mma: "",
    operator: "IntegrateWithBounds",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<span class='mq-math-mode qq-mq-int'><span class='mq-int mq-non-leaf'><big>∫</big><span class='mq-supsub mq-non-leaf qq-mq-int-supsub' style='vertical-align:0px'><span class='mq-sup'><span class='mq-sup-inner'><var>b</var></span></span><span class='mq-sub'><var>a</var></span><span style='display:inline-block;width:0'></span></span></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Integrate over given bounds",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\lim",
    mma: "",
    operator: "Limit",
    string: "Limit",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "lim",
    tooltip: "Limit",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\infin",
    mma: "",
    operator: "Infinity",
    string: "Infinity",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "∞",
    tooltip: "Infinity",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\infin",
    mma: "",
    operator: "infinity",
    string: "Infinity",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "∞",
    tooltip: "Infinity",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "Let",
    string: "Let",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Let",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\partial",
    mma: "",
    operator: "Partial Derivative Sign",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "∂",
    tooltip: "Partial Derivative",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "Dependent ",
    mma: "",
    operator: "Dependent",
    string: "Dependent",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "Dependent",
    tooltip: "Dependent System",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "Inconsistent",
    mma: "",
    operator: "Inconsistent",
    string: "Inconsistent",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "Inconsistent",
    tooltip: "Inconsistent System",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "NoSolution",
    mma: "",
    operator: "NoSolution",
    string: "No Solution",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "No Solution",
    tooltip: "No Solution",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "Solution",
    mma: "",
    operator: "Solution",
    string: "Solution",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "Solution",
    tooltip: "Solution",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: true,
    enabled: false,
    latex: "NotSolution",
    mma: "",
    operator: "NotSolution",
    string: "Not Solution",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "Not Solution",
    tooltip: "Not Solution",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\e",
    mma: "E",
    operator: "E",
    string: "e",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "𝑒",
    tooltip: "The number 𝑒",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\pi",
    mma: "pi",
    operator: "pi",
    string: "pi",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "π",
    tooltip: "The number π",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\#",
    mma: "",
    operator: "Factorial",
    string: "!",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "!",
    tooltip: "Factorial",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "GCF",
    mma: "",
    operator: "GCF",
    string: "GCF",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Greatest Common Factor",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "\\sum_{a=1}^b",
    mma: "",
    operator: "Sigma",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "∑",
    tooltip: "Summation, Sigma",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ft",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Feet",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "in",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Inches",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "m",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Meters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "mi",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Miles",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "L",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Liters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ml",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Milliliters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "yd",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Yard",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "km",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kilometers",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "lb",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Pounds",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "oz",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Ounces",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "kg",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kilograms",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "g",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Grams",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ton",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Short Tons",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "c",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cups",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "h",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Hours",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "cm",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Centimeters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "qt",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Quarts",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "pt",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Pints",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "gal",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Gallons",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "s",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Seconds",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "min",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Minutes",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "C",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Celsius",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "F",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Fahrenheit",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "K",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kelvin",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "W",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Watts",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "Wh",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Watt Hours",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "GW",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Gigawatts",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "MW",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Megawatts",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "kW",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kilowatts",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "GWh",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Gigawatt Hours",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "MWh",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Megawatt Hours",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "kWh",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kilowatt Hours",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "kWmin",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Kilowatt Minutes",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "mm",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Millimeters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "cm^3",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>cm</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>3</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cubic Centimeters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "km^3",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>km</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>3</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cubic Kilometers",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ft^3",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>ft</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>3</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cubic Feet",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "in^3",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>in</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>3</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cubic Inches",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "m^3",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>m</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>3</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Cubic Meters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ft^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>ft</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Feet",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "yd^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>yd</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Yards",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "in^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>in</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Inches",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "km^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>km</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Kilometers",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "mi^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>mi</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Millimeters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: " cm^2 ",
    mma: "",
    operator: "cm^2",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html:
      "<var>cm</var><span class='mq-supsub mq-non-leaf mq-sup-only'><span class='mq-sup'><var>2</var></span></span>",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Square Centimeters",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "ac",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Acres",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: "",
    mma: "",
    operator: "t",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "",
    tooltip: "Metric Tons",
  },
  {
    method: "write",
    cursorShift: "",
    atomic: false,
    enabled: false,
    latex: " fl oz ",
    mma: "",
    operator: "fl oz",
    string: "",
    symbol_latex: "",
    symbol_style: {},
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_svg: "",
    symbol_utf8: "fl oz",
    tooltip: "Fluid Ounces",
  },
];
