export const specialKeys = [
  {
    operator: "Backspace",
    string: "",
    latex: "",
    mma: "",
    symbol_utf8: "←",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    innerHTML: "←",
    tooltip: "Backspace",
  },
  {
    operator: "Clear",
    string: "",
    latex: "",
    mma: "",
    symbol_utf8: "C",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    innerHTML: "C",
    tooltip: "Clear Step",
  },
  {
    operator: "Space",
    string: "",
    latex: "",
    mma: "",
    symbol_utf8: "␣",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    innerHTML: "␣",
    tooltip: "Space",
  },
  {
    operator: "Equals",
    string: "",
    latex: "api.write('=')",
    mma: "",
    symbol_utf8: "=",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    innerHTML: "=",
    tooltip: "Equals",
  },
];
