export const stdOperators = [
  {
    atomic: false,
    cursorShift: "",
    enabled: false,
    latex: "\\divide",
    method: "cmd",
    mma: "/",
    operator: "divide",
    string: "÷",
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_latex: "÷",
    symbol_style: {
      background: "none",
      fontSize: ".6rem",
    },
    symbol_svg: "",
    symbol_utf8: "÷",
    tooltip: "Divide",
  },
  {
    atomic: false,
    cursorShift: "",
    enabled: false,
    latex: "\\ast",
    method: "cmd",
    mma: "*",
    operator: "Multiply",
    string: "*",
    symbol_html: "",
    symbol_icon: "",
    symbol_img: "",
    symbol_latex: "*",
    symbol_style: {
      background: "none",
      fontSize: ".6rem",
    },
    symbol_svg: "",
    symbol_utf8: "*",
    tooltip: "Multiply",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    operator: "minus",
    string: "-",
    latex: "-",
    mma: "-",
    symbol_latex: "-",
    symbol_style: { background: "none", fontSize: ".6rem" },
    symbol_utf8: "-",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    tooltip: "Subtract",
  },
  {
    method: "cmd",
    cursorShift: "",
    atomic: false,
    enabled: false,
    operator: "plus",
    string: "+",
    latex: "+",
    mma: "+",
    symbol_latex: "+",
    symbol_style: { background: "none", fontSize: ".6rem" },
    symbol_utf8: "+",
    symbol_icon: "",
    symbol_svg: "",
    symbol_img: "",
    symbol_html: "",
    tooltip: "Add",
  },
];
