/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./models/FoxyFuka.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function FoxyFuka(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/FoxyFuka.glb");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <primitive object={nodes.mixamorigHips} />
          <group name="duanxiu">
            <skinnedMesh
              castShadow
              name="Mesh002"
              geometry={nodes.Mesh002.geometry}
              material={materials.yifu}
              skeleton={nodes.Mesh002.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh002_1"
              geometry={nodes.Mesh002_1.geometry}
              material={materials.yifu_bian}
              skeleton={nodes.Mesh002_1.skeleton}
            />
          </group>
          <group name="head1">
            <skinnedMesh
              castShadow
              name="Mesh018"
              geometry={nodes.Mesh018.geometry}
              material={materials.face}
              skeleton={nodes.Mesh018.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Mesh018_1"
              geometry={nodes.Mesh018_1.geometry}
              material={materials.yifu_bian}
              skeleton={nodes.Mesh018_1.skeleton}
            />
          </group>
          <skinnedMesh
            castShadow
            name="jiemao_L"
            geometry={nodes.jiemao_L.geometry}
            material={materials.lambert3}
            skeleton={nodes.jiemao_L.skeleton}
          />
          <skinnedMesh
            castShadow
            name="jiemao_R"
            geometry={nodes.jiemao_R.geometry}
            material={materials.lambert3}
            skeleton={nodes.jiemao_R.skeleton}
          />
          <skinnedMesh
            castShadow
            name="kouzi"
            geometry={nodes.kouzi.geometry}
            material={materials.hua}
            skeleton={nodes.kouzi.skeleton}
          />
          <skinnedMesh
            castShadow
            name="meimao_L"
            geometry={nodes.meimao_L.geometry}
            material={materials.meimao1}
            skeleton={nodes.meimao_L.skeleton}
          />
          <skinnedMesh
            castShadow
            name="meimao_R"
            geometry={nodes.meimao_R.geometry}
            material={materials.meimao1}
            skeleton={nodes.meimao_R.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly1"
            geometry={nodes.nurbsToPoly1.geometry}
            material={materials.shetou}
            skeleton={nodes.nurbsToPoly1.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly10"
            geometry={nodes.nurbsToPoly10.geometry}
            material={materials.blinn4}
            skeleton={nodes.nurbsToPoly10.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly11"
            geometry={nodes.nurbsToPoly11.geometry}
            material={materials.ya}
            skeleton={nodes.nurbsToPoly11.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly12"
            geometry={nodes.nurbsToPoly12.geometry}
            material={materials.ya}
            skeleton={nodes.nurbsToPoly12.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly2"
            geometry={nodes.nurbsToPoly2.geometry}
            material={materials.shetou}
            skeleton={nodes.nurbsToPoly2.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly3"
            geometry={nodes.nurbsToPoly3.geometry}
            material={materials.eye_cornea1}
            skeleton={nodes.nurbsToPoly3.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly4"
            geometry={nodes.nurbsToPoly4.geometry}
            material={materials.eye_pupil1}
            skeleton={nodes.nurbsToPoly4.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly5"
            geometry={nodes.nurbsToPoly5.geometry}
            material={materials.blinn2}
            skeleton={nodes.nurbsToPoly5.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly6"
            geometry={nodes.nurbsToPoly6.geometry}
            material={materials.blinn4}
            skeleton={nodes.nurbsToPoly6.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly7"
            geometry={nodes.nurbsToPoly7.geometry}
            material={materials.eye_cornea1}
            skeleton={nodes.nurbsToPoly7.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly8"
            geometry={nodes.nurbsToPoly8.geometry}
            material={materials.eye_pupil1}
            skeleton={nodes.nurbsToPoly8.skeleton}
          />
          <skinnedMesh
            castShadow
            name="nurbsToPoly9"
            geometry={nodes.nurbsToPoly9.geometry}
            material={materials.blinn2}
            skeleton={nodes.nurbsToPoly9.skeleton}
          />
          <skinnedMesh
            castShadow
            name="qunzi"
            geometry={nodes.qunzi.geometry}
            material={materials.yifu}
            skeleton={nodes.qunzi.skeleton}
          />
          <skinnedMesh
            castShadow
            name="tongue"
            geometry={nodes.tongue.geometry}
            material={materials.shetou}
            skeleton={nodes.tongue.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/FoxyFuka.glb");
